//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 [Rancher Labs, Inc](https://rancher.com).

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEAuthenticatingProxy) DeepCopyInto(out *CCEAuthenticatingProxy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEAuthenticatingProxy.
func (in *CCEAuthenticatingProxy) DeepCopy() *CCEAuthenticatingProxy {
	if in == nil {
		return nil
	}
	out := new(CCEAuthenticatingProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEAuthentication) DeepCopyInto(out *CCEAuthentication) {
	*out = *in
	out.AuthenticatingProxy = in.AuthenticatingProxy
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEAuthentication.
func (in *CCEAuthentication) DeepCopy() *CCEAuthentication {
	if in == nil {
		return nil
	}
	out := new(CCEAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEClusterConfig) DeepCopyInto(out *CCEClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEClusterConfig.
func (in *CCEClusterConfig) DeepCopy() *CCEClusterConfig {
	if in == nil {
		return nil
	}
	out := new(CCEClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEClusterConfigList) DeepCopyInto(out *CCEClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CCEClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEClusterConfigList.
func (in *CCEClusterConfigList) DeepCopy() *CCEClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(CCEClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEClusterConfigSpec) DeepCopyInto(out *CCEClusterConfigSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.HostNetwork = in.HostNetwork
	out.ContainerNetwork = in.ContainerNetwork
	in.EniNetwork.DeepCopyInto(&out.EniNetwork)
	out.Authentication = in.Authentication
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.PublicIP = in.PublicIP
	out.NatGateway = in.NatGateway
	out.ExtendParam = in.ExtendParam
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]CCENodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedNodePoolIDs != nil {
		in, out := &in.CreatedNodePoolIDs, &out.CreatedNodePoolIDs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEClusterConfigSpec.
func (in *CCEClusterConfigSpec) DeepCopy() *CCEClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CCEClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEClusterConfigStatus) DeepCopyInto(out *CCEClusterConfigStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]CCEClusterEndpoints, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEClusterConfigStatus.
func (in *CCEClusterConfigStatus) DeepCopy() *CCEClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CCEClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEClusterEndpoints) DeepCopyInto(out *CCEClusterEndpoints) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEClusterEndpoints.
func (in *CCEClusterEndpoints) DeepCopy() *CCEClusterEndpoints {
	if in == nil {
		return nil
	}
	out := new(CCEClusterEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEClusterExtendParam) DeepCopyInto(out *CCEClusterExtendParam) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEClusterExtendParam.
func (in *CCEClusterExtendParam) DeepCopy() *CCEClusterExtendParam {
	if in == nil {
		return nil
	}
	out := new(CCEClusterExtendParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEClusterPublicIP) DeepCopyInto(out *CCEClusterPublicIP) {
	*out = *in
	out.Eip = in.Eip
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEClusterPublicIP.
func (in *CCEClusterPublicIP) DeepCopy() *CCEClusterPublicIP {
	if in == nil {
		return nil
	}
	out := new(CCEClusterPublicIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEContainerNetwork) DeepCopyInto(out *CCEContainerNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEContainerNetwork.
func (in *CCEContainerNetwork) DeepCopy() *CCEContainerNetwork {
	if in == nil {
		return nil
	}
	out := new(CCEContainerNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEEip) DeepCopyInto(out *CCEEip) {
	*out = *in
	out.Bandwidth = in.Bandwidth
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEEip.
func (in *CCEEip) DeepCopy() *CCEEip {
	if in == nil {
		return nil
	}
	out := new(CCEEip)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEEipBandwidth) DeepCopyInto(out *CCEEipBandwidth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEEipBandwidth.
func (in *CCEEipBandwidth) DeepCopy() *CCEEipBandwidth {
	if in == nil {
		return nil
	}
	out := new(CCEEipBandwidth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEEniNetwork) DeepCopyInto(out *CCEEniNetwork) {
	*out = *in
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEEniNetwork.
func (in *CCEEniNetwork) DeepCopy() *CCEEniNetwork {
	if in == nil {
		return nil
	}
	out := new(CCEEniNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEHostNetwork) DeepCopyInto(out *CCEHostNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEHostNetwork.
func (in *CCEHostNetwork) DeepCopy() *CCEHostNetwork {
	if in == nil {
		return nil
	}
	out := new(CCEHostNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCENatGateway) DeepCopyInto(out *CCENatGateway) {
	*out = *in
	out.SNatRuleEIP = in.SNatRuleEIP
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCENatGateway.
func (in *CCENatGateway) DeepCopy() *CCENatGateway {
	if in == nil {
		return nil
	}
	out := new(CCENatGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCENodeExtendParam) DeepCopyInto(out *CCENodeExtendParam) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCENodeExtendParam.
func (in *CCENodeExtendParam) DeepCopy() *CCENodeExtendParam {
	if in == nil {
		return nil
	}
	out := new(CCENodeExtendParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCENodePool) DeepCopyInto(out *CCENodePool) {
	*out = *in
	in.NodeTemplate.DeepCopyInto(&out.NodeTemplate)
	out.Autoscaling = in.Autoscaling
	if in.PodSecurityGroups != nil {
		in, out := &in.PodSecurityGroups, &out.PodSecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CustomSecurityGroups != nil {
		in, out := &in.CustomSecurityGroups, &out.CustomSecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCENodePool.
func (in *CCENodePool) DeepCopy() *CCENodePool {
	if in == nil {
		return nil
	}
	out := new(CCENodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCENodePoolNodeAutoscaling) DeepCopyInto(out *CCENodePoolNodeAutoscaling) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCENodePoolNodeAutoscaling.
func (in *CCENodePoolNodeAutoscaling) DeepCopy() *CCENodePoolNodeAutoscaling {
	if in == nil {
		return nil
	}
	out := new(CCENodePoolNodeAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCENodePublicIP) DeepCopyInto(out *CCENodePublicIP) {
	*out = *in
	if in.IDs != nil {
		in, out := &in.IDs, &out.IDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Eip = in.Eip
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCENodePublicIP.
func (in *CCENodePublicIP) DeepCopy() *CCENodePublicIP {
	if in == nil {
		return nil
	}
	out := new(CCENodePublicIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCENodeTemplate) DeepCopyInto(out *CCENodeTemplate) {
	*out = *in
	out.RootVolume = in.RootVolume
	if in.DataVolumes != nil {
		in, out := &in.DataVolumes, &out.DataVolumes
		*out = make([]CCENodeVolume, len(*in))
		copy(*out, *in)
	}
	in.PublicIP.DeepCopyInto(&out.PublicIP)
	out.ExtendParam = in.ExtendParam
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCENodeTemplate.
func (in *CCENodeTemplate) DeepCopy() *CCENodeTemplate {
	if in == nil {
		return nil
	}
	out := new(CCENodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCENodeVolume) DeepCopyInto(out *CCENodeVolume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCENodeVolume.
func (in *CCENodeVolume) DeepCopy() *CCENodeVolume {
	if in == nil {
		return nil
	}
	out := new(CCENodeVolume)
	in.DeepCopyInto(out)
	return out
}
